### ISSUE TITLE
Fluqid Mach. Basic Equation

### ISSUE THREAD

**Issue by 271828182846** [IBM-Bluemix-Docs/runtimes#100] opened 2019-04-15 13:43 UTC
`E`.  _'h,v_  = (h.c)' _`Nm`_& ***λ*** *

**Comment by 271828182846** [comment] 2019-04-15 13:43
Duplicate of #99

**Comment by preetisawant** [comment] 2019-06-18 17:30
Closing as duplicate of issue #99

**Closed by preetisawant** 2019-06-18 17:30 UTC
